[package]
name = "structural_types"
version = "0.1.0"
edition = "2021"

[dependencies]
z3 = "0.12.1"
lalrpop-util = { version = "0.20", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.20"
